secrets:
  index.php:
    external: true
services:
  phpinfo:
    deploy:
      mode: replicated
      replicas: 2
      restart_policy:
        condition: any
    command:
      - -f
      - index.php
      - -S
      - 0.0.0.0:8080
    entrypoint:
      - php
    image: php
    ports:
      - 8080
    read_only: true
    secrets:
      - source: index.php
        target: /app/index.php
        mode: 0400
        uid: '65534'
    user: nobody
    working_dir: /app/
version: '3.8'
