apiVersion: v1
kind: Pod
metadata:
  labels:
    app: phpinfo
  name: phpinfo-pod
  namespace: phpinfo
spec:
  containers:
    - args:
        - -f
        - index.php
        - -S
        - 0.0.0.0:8080
      command:
        - php
      image: php:alpine
      name: phpinfo-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /app/index.php
          name: phpinfo-volume
          readOnly: true
          subPath: index.php
      workingDir: /app/
  restartPolicy: Always
  securityContext:
    runAsUser: 65534
  volumes:
    - name: phpinfo-volume
      secret:
        defaultMode: 0444
        items:
          - key: index.php
            mode: 0444
            path: index.php
        secretName: phpinfo-secret
