version: "3.3"
services:
  backend:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydbuser
      MYSQL_PASSWORD: myuserpassword

  frontend:
     depends_on:
       - backend
     image: wordpress:latest
     volumes:
       - wordpress_data:/var/www/html
     ports:
       - "8000:80"
     restart: always


volumes:
  db_data:
    driver: flocker
    driver_opts:
      size: "1GiB"
  wordpress_data:
    driver: flocker
    driver_opts:
      size: "1Gib"
